spring:
  application:
    name: msclientes
    
server:
  port: 0
  
eureka:
  client:
    service-url: 
      defaultZone:  http://cursoms-eureka-user:12345678@${EUREKA_SERVER}:8761/eureka
                        #nome-user eurila; senha eureka@ caminho do servidor
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}



management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log